# Data Science Assignment – Linear Algebra & Regression

## 1. Matrix Operations

In [1]:
import numpy as np

A = np.array([[2, -1],
              [0,  3]])

B = np.array([[1,  2],
              [-3, 4]])

A + B, A @ B, 3*A - 2*B

(array([[ 3,  1],
        [-3,  7]]),
 array([[ 5,  0],
        [-9, 12]]),
 array([[ 4, -7],
        [ 6,  1]]))

## 2. Determinant and Inverse

In [2]:
np.linalg.det(A), np.linalg.inv(A)

(np.float64(6.0),
 array([[0.5       , 0.16666667],
        [0.        , 0.33333333]]))

## 3. Eigenvalues and Eigenvectors

In [3]:
C = np.array([[4, 1],
              [-2, 1]])

np.linalg.eig(C)

EigResult(eigenvalues=array([3., 2.]), eigenvectors=array([[ 0.70710678, -0.4472136 ],
       [-0.70710678,  0.89442719]]))

## 4. Linear Regression Using Normal Equation

In [4]:
X = np.array([[4, 1.5, 100],
              [6, 2.0, 150]])

y = np.array([[20],
              [30]])

beta = np.linalg.pinv(X) @ y
beta

array([[7.98722045e-03],
       [2.84217094e-14],
       [1.99680511e-01]])

In [5]:
x_new = np.array([[8, 3.0, 200]])
x_new @ beta

array([[40.]])